apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: app-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: registry.gitlab.au.dk/swwao/demo-projs/typescript-mongodb-crud
          resources:
            requests:
              cpu: "100m" # 10% of a CPU core
              memory: "256Mi" # 256 Mebibytes
            limits:
              cpu: "500m" # 50% of a CPU core
              memory: "1Gi" # 1 Gibibyte
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGODB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_DBNAME
            - name: MONGODB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_HOSTNAME
            - name: REL_URL_PATH
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REL_URL_PATH
      imagePullSecrets:
        - name: my-registry-credentials
