apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-app-ingress
  namespace: app-space
spec:
  ingressClassName: "nginx"
  rules:
    - host: "swwao.courses.orbit.au.dk"
      http:
        paths:
          - pathType: Prefix
            path: "/grp-9/myapp"
            backend:
              service:
                name: node-app-service
                port:
                  number: 80
