# mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: app-space
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            requests:
              cpu: "100m" # 10% of a CPU core
              memory: "256Mi" # 256 Mebibytes
            limits:
              cpu: "500m" # 50% of a CPU core
              memory: "1Gi" # 1 Gibibyte
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_HOSTNAME
            - name: MONGODB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_DBNAME
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
